services:
  train-sai:
    build:
      context: ..
      dockerfile: ./docker/Dockerfile
    image: sai-training
    container_name: sai-training
    volumes:
      - ../configs:/configs
      - ../output:/output
      - ../datasets:/data
    command: /bin/sh -c "python ./tools/train_net.py --resume --dataset-dir /data/barley --config-file /configs/mask_rcnn_barley_2.yaml OUTPUT_DIR /output/barley_v3"
    shm_size: 2gb
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [ gpu ]
