services:
  train-sai:
    build:
      context: ..
      dockerfile: ./docker/Dockerfile
    image: sai-training
    container_name: sai-training
    volumes:
      - ../configs:/configs
      - ../output:/output
      - /mnt/data/stomata:/data
    command: /bin/sh -c "python ./tools/train_net.py --num-gpus 2 --resume --dataset-dir /data/arabidopsis_v3 --config-file /configs/mask_rcnn_arabidopsis_2.yaml OUTPUT_DIR /output/arabidopsis_v3"
    shm_size: 2gb
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 2
              capabilities: [ gpu ]
