_BASE_: "Base-RCNN-FPN.yaml"
MODEL:
  WEIGHTS: "detectron2://ImageNetPretrained/MSRA/R-50.pkl"
  MASK_ON: False
  RESNETS:
    DEPTH: 50
INPUT:
  CROP:
    ENABLED: True
    SIZE: [0.5, 0.5]
TEST:
  EVAL_PERIOD: 5000
OUTPUT_DIR: output/detection/R_50
