_BASE_: "Base-RCNN-FPN.yaml"
MODEL:
  WEIGHTS: "detectron2://ImageNetPretrained/MSRA/R-50.pkl"
  MASK_ON: True
  KEYPOINT_ON: True
  RESNETS:
    DEPTH: 50
  ROI_HEADS:
    NUM_CLASSES: 2
  ROI_KEYPOINT_HEAD:
    NUM_KEYPOINTS: 2
DATASETS:
  TRAIN: ("stoma_train",)
  TEST: ("stoma_val",)
TEST:
  EVAL_PERIOD: 5000
  KEYPOINT_OKS_SIGMAS: [0.02, 0.02]
OUTPUT_DIR: gs://aiml-sscv-data/stomata/output/mask/R_50_FPN_higher_low_cosine
SOLVER:
  IMS_PER_BATCH: 2
  MAX_ITER: 100000
  LR_SCHEDULER_NAME: WarmupCosineLR
INPUT:
  MIN_SIZE_TRAIN: (320, 2048)
  MIN_SIZE_TEST: 0
  MAX_SIZE_TRAIN: 3000
  MAX_SIZE_TEST: 3000
